<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AdminPasswordController;
use App\Http\Controllers\AdminTwoFactorController;
use App\Http\Controllers\AdminBillingController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminEmailTemplateController;
use App\Http\Controllers\AdminOrderEntryController;
use App\Http\Controllers\AdminOrderDetailController;
use App\Http\Controllers\AdminOrdersController;
use App\Http\Controllers\AdminPeopleController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\AdminQuickQuoteController;
use App\Http\Controllers\AdminSimulationController;
use App\Http\Controllers\AdminSiteOfferController;
use App\Http\Controllers\AdminSitePaymentController;
use App\Http\Controllers\AdminSitePricingController;
use App\Http\Controllers\AdminToolsController;
use App\Http\Controllers\AuthLandingController;
use App\Http\Controllers\CustomerAccountController;
use App\Http\Controllers\CustomerAuthController;
use App\Http\Controllers\CustomerTwoFactorController;
use App\Http\Controllers\CustomerOrderEntryController;
use App\Http\Controllers\CustomerPasswordController;
use App\Http\Controllers\CustomerPaymentController;
use App\Http\Controllers\CustomerPortalController;
use App\Http\Controllers\CustomerRegistrationController;
use App\Http\Controllers\CustomerSiteController;
use App\Http\Controllers\TeamAuthController;
use App\Http\Controllers\TeamDashboardController;
use App\Http\Controllers\TeamDesignInfoController;
use App\Http\Controllers\TeamOrderDetailController;
use App\Http\Controllers\TeamOrdersController;
use App\Http\Controllers\TeamQuickQuoteController;
use App\Http\Controllers\TeamSupervisorController;
use App\Http\Controllers\UploadController;
use Illuminate\Support\Facades\Route;

$adminPrefix = trim((string) config('sites.admin_prefix', 'admin'), '/');
$internalPortalPath = trim((string) config('sites.internal_portal_path', 'portal'), '/');

Route::middleware('detect.site')->group(function () use ($adminPrefix, $internalPortalPath) {
    Route::get('/robots.txt', [CustomerSiteController::class, 'robots']);
    Route::get('/sitemap.xml', [CustomerSiteController::class, 'sitemap']);
    Route::get('/', [CustomerSiteController::class, 'home']);
    Route::get('/index.php', [CustomerSiteController::class, 'home']);
    Route::get('/home.php', [CustomerSiteController::class, 'home']);
    Route::get('/index-new.php', [CustomerSiteController::class, 'home']);
    Route::get('/about-us.php', [CustomerSiteController::class, 'about']);
    Route::get('/our-quality.php', [CustomerSiteController::class, 'quality']);
    Route::get('/work-process.php', [CustomerSiteController::class, 'workProcess']);
    Route::get('/our-services.php', [CustomerSiteController::class, 'services']);
    Route::get('/embroidery-digitizing.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', 'embroidery-digitizing');
    Route::get('/3d-puff-embroidery-digitizing.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', '3d-puff-embroidery-digitizing');
    Route::get('/applique-embroidery-digitizing.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', 'applique-embroidery-digitizing');
    Route::get('/chain-stitch-embroidery-digitizing.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', 'chain-stitch-embroidery-digitizing');
    Route::get('/photo-digitizing.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', 'photo-digitizing');
    Route::get('/vector-art.php', [CustomerSiteController::class, 'servicePage'])->defaults('section', 'vector-art');
    Route::get('/formats.php', [CustomerSiteController::class, 'formats']);
    Route::redirect('/machine-embroidery-formats.php', '/formats.php#embroidery-formats');
    Route::redirect('/vector-file-formats.php', '/formats.php#vector-formats');
    Route::get('/price-plan.php', [CustomerSiteController::class, 'pricing']);
    Route::get('/payment-options.php', [CustomerSiteController::class, 'paymentOptions']);
    Route::get('/privacy-policy.php', [CustomerSiteController::class, 'privacyPolicy']);
    Route::get('/terms.php', [CustomerSiteController::class, 'terms']);
    Route::match(['get', 'post'], '/instant-payment.php', [CustomerPaymentController::class, 'instantPaymentLanding']);
    Route::match(['get', 'post'], '/instant-payment-paypal.php', [CustomerPaymentController::class, 'instantPaymentLanding']);
    Route::get('/contact-us.php', [CustomerSiteController::class, 'contact']);
    Route::post('/contact-us.php', [CustomerSiteController::class, 'sendContact']);
    Route::get('/simulate-2checkout/{transaction}/checkout', [CustomerPaymentController::class, 'showTwocheckoutSimulator'])->middleware('customer.auth');
    Route::match(['get', 'post'], '/simulate-2checkout/{transaction}', [CustomerPaymentController::class, 'simulateTwocheckout'])->middleware('customer.auth');
    Route::get('/dashboard.php', [CustomerPortalController::class, 'dashboard'])->middleware('customer.auth');
    Route::get('/new-order.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/new-order.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/vector-order.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/vector-order.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/quote.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/quote.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/digitizing_quote.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/digitizing_quote.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/digitizing-quote.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/digitizing-quote.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/vector_quote.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/vector_quote.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/vector-quote.php', [CustomerOrderEntryController::class, 'create'])->middleware('customer.auth');
    Route::post('/vector-quote.php', [CustomerOrderEntryController::class, 'store'])->middleware('customer.auth');
    Route::get('/edit-order.php', [CustomerOrderEntryController::class, 'edit'])->middleware('customer.auth');
    Route::post('/edit-order.php', [CustomerOrderEntryController::class, 'update'])->middleware('customer.auth');
    Route::get('/edit-quote.php', [CustomerOrderEntryController::class, 'edit'])->middleware('customer.auth');
    Route::post('/edit-quote.php', [CustomerOrderEntryController::class, 'update'])->middleware('customer.auth');
    Route::get('/disapprove-order.php', [CustomerOrderEntryController::class, 'revision'])->middleware('customer.auth');
    Route::post('/disapprove-order.php', [CustomerOrderEntryController::class, 'submitRevision'])->middleware('customer.auth');
    Route::get('/view-orders.php', [CustomerPortalController::class, 'orders'])->middleware('customer.auth');
    Route::get('/view-order-detail.php', [CustomerPortalController::class, 'showOrder'])->middleware('customer.auth');
    Route::get('/view-orderpaid-details.php', [CustomerPortalController::class, 'showOrder'])->middleware('customer.auth');
    Route::get('/view-quotes.php', [CustomerPortalController::class, 'quotes'])->middleware('customer.auth');
    Route::get('/view-quote-detail.php', [CustomerPortalController::class, 'showQuote'])->middleware('customer.auth');
    Route::get('/view-billing.php', [CustomerPortalController::class, 'billing'])->middleware('customer.auth');
    Route::get('/view-archive-orders.php', [CustomerPortalController::class, 'archive'])->middleware('customer.auth');
    Route::get('/view-paid-orders.php', [CustomerAccountController::class, 'paidAdvanceOrders'])->middleware('customer.auth');
    Route::get('/view-invoices.php', [CustomerAccountController::class, 'invoices'])->middleware('customer.auth');
    Route::get('/view-invoice-detail.php', [CustomerAccountController::class, 'invoiceDetail'])->middleware('customer.auth');
    Route::get('/referral-invoice.php', [CustomerAccountController::class, 'referralInvoices'])->middleware('customer.auth');
    Route::get('/refund-apply.php', [CustomerAccountController::class, 'refundForm'])->middleware('customer.auth');
    Route::post('/refund-apply.php', [CustomerAccountController::class, 'submitRefund'])->middleware('customer.auth');
    Route::get('/my-profile.php', [CustomerAccountController::class, 'profile'])->middleware('customer.auth');
    Route::post('/my-profile.php', [CustomerAccountController::class, 'updateProfile'])->middleware('customer.auth');
    Route::post('/my-profile/password', [CustomerAccountController::class, 'updatePassword'])->middleware('customer.auth');
    Route::post('/my-profile/2fa', [CustomerAccountController::class, 'toggleTwoFactor'])->middleware('customer.auth');
    Route::get('/login-verify.php', [CustomerTwoFactorController::class, 'show'])->name('customer.2fa.show');
    Route::post('/login-verify.php', [CustomerTwoFactorController::class, 'verify'])->name('customer.2fa.verify');
    Route::post('/login-verify-resend.php', [CustomerTwoFactorController::class, 'resend'])->name('customer.2fa.resend');
    Route::get('/download.php', [CustomerPortalController::class, 'download'])->middleware('customer.auth');
    Route::get('/preview.php', [CustomerPortalController::class, 'preview'])->middleware('customer.auth');
    Route::post('/orders/{order}/approve', [CustomerPortalController::class, 'approve'])->middleware('customer.auth');
    Route::post('/orders/{order}/cancel', [CustomerPortalController::class, 'cancelOrder'])->middleware('customer.auth');
    Route::post('/quotes/{order}/switch-to-order', [CustomerPortalController::class, 'switchQuoteToOrder'])->middleware('customer.auth');
    Route::get('/approved-order.php', [CustomerPortalController::class, 'approveCompatibility'])->middleware('customer.auth');
    Route::post('/quotes/{order}/feedback', [CustomerPortalController::class, 'quoteFeedback'])->middleware('customer.auth');
    Route::post('/quotes/{order}/delete', [CustomerPortalController::class, 'deleteQuote'])->middleware('customer.auth');
    Route::post('/view-billing.php/pay-all', [CustomerPaymentController::class, 'startOutstanding'])->middleware('customer.auth');
    Route::post('/view-billing.php/{billing}/pay', [CustomerPaymentController::class, 'startSingle'])->middleware('customer.auth');
    Route::get('/member-offer.php', [CustomerPaymentController::class, 'showSignupOffer'])->middleware('customer.auth');
    Route::post('/member-offer.php/pay', [CustomerPaymentController::class, 'startSignupOffer'])->middleware('customer.auth');
    Route::match(['get', 'post'], '/payment.php', [CustomerPaymentController::class, 'legacyDirectPayment'])->middleware('customer.auth');
    Route::match(['get', 'post'], '/payment-proceed.php', [CustomerPaymentController::class, 'legacyProceed']);
    Route::match(['get', 'post'], '/successpay.php', [CustomerPaymentController::class, 'handleReturn']);
    Route::match(['get', 'post'], '/successpay1.php', [CustomerPaymentController::class, 'handleReturn']);
    Route::match(['get', 'post'], '/successpay-paypal.php', [CustomerPaymentController::class, 'handleReturn']);
    Route::post('/payment-notification.php', [CustomerPaymentController::class, 'handleNotification']);
    Route::post('/webhooks/stripe', [CustomerPaymentController::class, 'handleStripeWebhook']);

    Route::get('/'.$internalPortalPath, [AuthLandingController::class, 'show']);
    Route::get('/'.$internalPortalPath.'/index.php', [AuthLandingController::class, 'show']);

    Route::get('/sign-up.php', [CustomerRegistrationController::class, 'show']);
    Route::post('/sign-up.php', [CustomerRegistrationController::class, 'register']);
    Route::get('/confirmation_registration.php', [CustomerRegistrationController::class, 'activate']);
    Route::get('/resend-verification.php', [CustomerRegistrationController::class, 'showResend']);
    Route::post('/resend-verification.php', [CustomerRegistrationController::class, 'resend']);
    Route::get('/login', [CustomerAuthController::class, 'showLogin']);
    Route::get('/login.php', [CustomerAuthController::class, 'showLogin']);
    Route::post('/login', [CustomerAuthController::class, 'login']);
    Route::post('/login.php', [CustomerAuthController::class, 'login']);
    Route::get('/forget-password.php', [CustomerPasswordController::class, 'showForgot']);
    Route::post('/forget-password.php', [CustomerPasswordController::class, 'sendResetLink']);
    Route::get('/reset-password.php', [CustomerPasswordController::class, 'showReset']);
    Route::post('/reset-password.php', [CustomerPasswordController::class, 'reset']);
    Route::get('/logout.php', [CustomerAuthController::class, 'logout']);

    Route::get('/'.$adminPrefix, [AdminAuthController::class, 'showLogin']);
    Route::get('/'.$adminPrefix.'/login', [AdminAuthController::class, 'showLogin']);
    Route::post('/'.$adminPrefix.'/login', [AdminAuthController::class, 'login']);
    Route::get('/'.$adminPrefix.'/logout', [AdminAuthController::class, 'logout']);
    Route::post('/stop-simulated-session', [AdminSimulationController::class, 'stop']);
});

Route::get('/v', [AdminAuthController::class, 'showLogin']);
Route::get('/v/index.php', [AdminAuthController::class, 'showLogin'])->name('admin.login');
Route::post('/v/login', [AdminAuthController::class, 'login']);
Route::get('/v/logout.php', [AdminAuthController::class, 'logout']);
Route::get('/v/login-2fa', [AdminTwoFactorController::class, 'show'])->name('admin.2fa.show');
Route::post('/v/login-2fa', [AdminTwoFactorController::class, 'verify'])->name('admin.2fa.verify');
Route::post('/v/login-2fa-resend', [AdminTwoFactorController::class, 'resend'])->name('admin.2fa.resend');
Route::get('/v/forgot-password', [AdminPasswordController::class, 'showForgot']);
Route::post('/v/forgot-password', [AdminPasswordController::class, 'sendResetLink']);
Route::get('/v/reset-password', [AdminPasswordController::class, 'showReset']);
Route::post('/v/reset-password', [AdminPasswordController::class, 'doReset']);

Route::middleware('admin.auth')->group(function () use ($adminPrefix) {
    Route::get('/welcome.php', [AdminDashboardController::class, 'index']);
    Route::get('/'.$adminPrefix.'/welcome', [AdminDashboardController::class, 'index']);
    Route::get('/v/welcome.php', [AdminDashboardController::class, 'index']);
    Route::match(['get', 'post'], '/v/orders.php', [AdminOrdersController::class, 'index']);
    Route::match(['get', 'post'], '/v/orders/{queue}', [AdminOrdersController::class, 'index']);
    Route::get('/v/create-order.php', [AdminOrderEntryController::class, 'create']);
    Route::post('/v/create-order.php', [AdminOrderEntryController::class, 'store']);
    Route::post('/v/create-order/price-preview', [AdminOrderEntryController::class, 'previewPrice']);
    Route::get('/v/show-all-orders.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'All Orders');
    Route::get('/v/new-orders.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'New Orders');
    Route::get('/v/disapproved-orders.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Disapproved Orders');
    Route::get('/v/assigned-orders.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Designer Orders');
    Route::get('/v/designer-completed-orders.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Designer Completed');
    Route::get('/v/approval-waiting-order.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Customer Approval Waiting');
    Route::get('/v/new-quotes.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'New Quotes');
    Route::get('/v/assigned-quotes.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Assigned Quotes');
    Route::get('/v/desinger-completed-quotes.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Designer Completed Quotes');
    Route::get('/v/completed-quotes.php', [AdminOrdersController::class, 'compatibilityListRedirect'])->defaults('page', 'Completed Quotes');
    Route::get('/v/view-order-detail.php', [AdminOrderDetailController::class, 'show']);
    Route::get('/v/view-order-detail-2.php', [AdminOrdersController::class, 'compatibilityDetailRedirect']);
    Route::get('/v/orders/{order}/detail/{page?}', [AdminOrderDetailController::class, 'showByRoute']);
    Route::post('/v/orders/{order}/delete', [AdminOrdersController::class, 'destroy']);
    Route::post('/v/orders/{order}/mark-paid', [AdminOrdersController::class, 'markPaid']);
    Route::post('/v/orders/{order}/approve', [AdminOrdersController::class, 'approve']);
    Route::post('/v/order-detail/comments', [AdminOrderDetailController::class, 'addComment']);
    Route::post('/v/comments/{comment}/delete', [AdminOrderDetailController::class, 'deleteComment']);
    Route::post('/v/order-detail/upload', [AdminOrderDetailController::class, 'uploadAttachment']);
    Route::get('/v/attachments/{attachment}/download', [AdminOrderDetailController::class, 'downloadAttachment']);
    Route::get('/v/attachments/{attachment}/preview', [AdminOrderDetailController::class, 'previewAttachment']);
    Route::get('/v/attachments/{attachment}/preview/raw', [AdminOrderDetailController::class, 'previewAttachment'])->defaults('raw', 1);
    Route::post('/v/attachments/{attachment}/delete', [AdminOrderDetailController::class, 'deleteAttachment']);
    Route::post('/v/order-detail/select-for-customer', [AdminOrderDetailController::class, 'selectFilesForCustomer']);
    Route::post('/v/order-detail/delivery-controls', [AdminOrderDetailController::class, 'saveDeliveryControls']);
    Route::post('/v/order-detail/respond-quote-negotiation', [AdminOrderDetailController::class, 'respondToQuoteNegotiation']);
    Route::post('/v/order-detail/convert-quote', [AdminOrderDetailController::class, 'convertQuoteToOrder']);
    Route::post('/v/order-detail/price-preview', [AdminOrderDetailController::class, 'previewPrice']);
    Route::post('/v/order-detail/complete', [AdminOrderDetailController::class, 'complete']);
    Route::get('/v/view-quick-order-detail.php', [AdminQuickQuoteController::class, 'show']);
    Route::post('/v/quick-order/comments', [AdminQuickQuoteController::class, 'addComment']);
    Route::post('/v/quick-comments/{comment}/delete', [AdminQuickQuoteController::class, 'deleteComment']);
    Route::get('/v/quick-attachments/{attachment}/download', [AdminQuickQuoteController::class, 'downloadAttachment']);
    Route::get('/v/quick-attachments/{attachment}/preview', [AdminQuickQuoteController::class, 'previewAttachment']);
    Route::get('/v/quick-attachments/{attachment}/preview/raw', [AdminQuickQuoteController::class, 'previewAttachment'])->defaults('raw', 1);
    Route::post('/v/quick-attachments/{attachment}/delete', [AdminQuickQuoteController::class, 'deleteAttachment']);
    Route::post('/v/quick-order/complete', [AdminQuickQuoteController::class, 'complete']);
    Route::match(['get', 'post'], '/v/all-payment-due.php', [AdminBillingController::class, 'due']);
    Route::match(['get', 'post'], '/v/payment-recieved.php', [AdminBillingController::class, 'received']);
    Route::post('/v/billing/{billing}/delete', [AdminBillingController::class, 'destroy']);
    Route::match(['get', 'post'], '/v/customer_list.php', [AdminPeopleController::class, 'customers']);
    Route::match(['get', 'post'], '/v/customer-approvals.php', [AdminPeopleController::class, 'pendingApprovals']);
    Route::post('/v/customers/{customer}/verify-email', [AdminPeopleController::class, 'verifyCustomerEmail']);
    Route::post('/v/customers/{customer}/approve', [AdminPeopleController::class, 'approveCustomer']);
    Route::post('/v/customers/{customer}/block', [AdminPeopleController::class, 'blockCustomer']);
    Route::post('/v/customers/{customer}/delete', [AdminPeopleController::class, 'deleteCustomer']);
    Route::match(['get', 'post'], '/v/show-all-teams.php', [AdminPeopleController::class, 'teams']);
    Route::post('/v/teams/{team}/disable', [AdminPeopleController::class, 'disableTeam']);
    Route::post('/v/teams/{team}/unlock', [AdminPeopleController::class, 'unlockTeam']);
    Route::match(['get', 'post'], '/v/customer_list_sikandar.php', [AdminPeopleController::class, 'customers']);
    Route::get('/v/customer-detail.php', [AdminProfileController::class, 'customerShow']);
    Route::post('/v/customers/{customer}/reset-password', [AdminProfileController::class, 'resetCustomerPassword']);
    Route::get('/v/edit-customer-detail.php', [AdminProfileController::class, 'customerEdit']);
    Route::post('/v/edit-customer-detail.php', [AdminProfileController::class, 'customerUpdate']);
    Route::get('/v/change-password.php', [AdminProfileController::class, 'adminPasswordForm']);
    Route::post('/v/change-password.php', [AdminProfileController::class, 'adminPasswordSave']);
    Route::get('/v/create-teams.php', [AdminProfileController::class, 'teamForm']);
    Route::post('/v/create-teams.php', [AdminProfileController::class, 'teamSave']);
    Route::get('/v/assign-order.php', [AdminProfileController::class, 'assignForm']);
    Route::post('/v/assign-order.php', [AdminProfileController::class, 'assignSave']);
    Route::match(['get', 'post'], '/v/payment-due-report.php', [AdminToolsController::class, 'dueReport']);
    Route::get('/v/payment-due-detail.php', [AdminToolsController::class, 'dueReportDetail']);
    Route::get('/v/pop-payment-due.php', [AdminToolsController::class, 'dueReportPopupRedirect']);
    Route::post('/v/payment-due-report/customer-pay', [AdminToolsController::class, 'dueReportPayCustomer']);
    Route::post('/v/payment-due-report/invoice/{billing}/pay', [AdminToolsController::class, 'dueReportPayInvoice']);
    Route::post('/v/payment-due-report/invoice/{billing}/apply-balance', [AdminToolsController::class, 'applyCustomerBalance']);
    Route::post('/v/payment-due-report/customer/apply-balance', [AdminToolsController::class, 'applyCustomerBalanceToCustomer']);
    Route::match(['get', 'post'], '/v/payment-recieved-report.php', [AdminToolsController::class, 'receivedReport']);
    Route::get('/v/payment-recieved-detail.php', [AdminToolsController::class, 'receivedReportDetail']);
    Route::get('/v/pop-payment-recieved.php', [AdminToolsController::class, 'receivedReportPopupRedirect']);
    Route::match(['get', 'post'], '/v/monthly-reports.php', [AdminToolsController::class, 'teamReport']);
    Route::match(['get', 'post'], '/v/login_history.php', [AdminToolsController::class, 'loginHistory']);
    Route::match(['get', 'post'], '/v/security-events.php', [AdminToolsController::class, 'securityEvents']);
    Route::match(['get', 'post'], '/v/block-customer_list.php', [AdminToolsController::class, 'blockedCustomers']);
    Route::post('/v/block-customer_list/{customer}/unblock', [AdminToolsController::class, 'unblockCustomer']);
    Route::post('/v/block-customer_list/{customer}/delete', [AdminToolsController::class, 'deleteBlockedCustomer']);
    Route::get('/v/blocked-ip-list.php', [AdminToolsController::class, 'blockedIps']);
    Route::post('/v/blocked-ip-list.php', [AdminToolsController::class, 'storeBlockedIp']);
    Route::match(['get', 'post'], '/v/block_ip.php', [AdminToolsController::class, 'blockedIps']);
    Route::post('/v/blocked-ip-list/{blockIp}/delete', [AdminToolsController::class, 'deleteBlockedIp']);
    Route::get('/v/transaction-history.php', [AdminToolsController::class, 'transactionHistory']);
    Route::get('/v/pay-now.php', [AdminToolsController::class, 'paymentForm']);
    Route::post('/v/pay-now.php', [AdminToolsController::class, 'paymentSave']);
    Route::get('/v/customer-lookup.php', [AdminToolsController::class, 'customerLookup']);
    Route::get('/v/customer-payment-inventory.php', [AdminToolsController::class, 'customerPaymentInventory']);
    Route::get('/v/notify-customers.php', [AdminToolsController::class, 'notifyCustomers']);
    Route::post('/v/notify-customers.php', [AdminToolsController::class, 'sendNotifyCustomers']);
    Route::get('/v/email-templates.php', [AdminEmailTemplateController::class, 'index']);
    Route::get('/v/email-templates-create.php', [AdminEmailTemplateController::class, 'create']);
    Route::post('/v/email-templates-create.php', [AdminEmailTemplateController::class, 'store']);
    Route::get('/v/email-templates/{template}/edit', [AdminEmailTemplateController::class, 'edit']);
    Route::post('/v/email-templates/{template}/edit', [AdminEmailTemplateController::class, 'update']);
    Route::post('/v/email-templates/{template}/delete', [AdminEmailTemplateController::class, 'destroy']);
    Route::get('/v/offer-claims.php', [AdminSiteOfferController::class, 'allClaims']);
    Route::get('/v/site-offers.php', [AdminSiteOfferController::class, 'index']);
    Route::get('/v/site-offers-create.php', [AdminSiteOfferController::class, 'create']);
    Route::post('/v/site-offers-create.php', [AdminSiteOfferController::class, 'store']);
    Route::get('/v/site-offers/{offer}/claims', [AdminSiteOfferController::class, 'claims']);
    Route::get('/v/site-offers/{offer}/edit', [AdminSiteOfferController::class, 'edit']);
    Route::post('/v/site-offers/{offer}/edit', [AdminSiteOfferController::class, 'update']);
    Route::post('/v/site-offers/{offer}/delete', [AdminSiteOfferController::class, 'destroy']);
    Route::get('/v/site-payments.php', [AdminSitePaymentController::class, 'index']);
    Route::post('/v/site-payments/{site}/edit', [AdminSitePaymentController::class, 'update']);
    Route::get('/v/site-pricing.php', [AdminSitePricingController::class, 'index']);
    Route::get('/v/site-pricing-create.php', [AdminSitePricingController::class, 'create']);
    Route::post('/v/site-pricing-create.php', [AdminSitePricingController::class, 'store']);
    Route::get('/v/site-pricing/{profile}/edit', [AdminSitePricingController::class, 'edit']);
    Route::post('/v/site-pricing/{profile}/edit', [AdminSitePricingController::class, 'update']);
    Route::post('/v/site-pricing/{profile}/delete', [AdminSitePricingController::class, 'destroy']);
    Route::post('/v/simulate-login/{user}', [AdminSimulationController::class, 'start']);
    Route::match(['get', 'post'], '/v/ordersquick.php', [AdminToolsController::class, 'quickQuotes']);
    Route::post('/v/ordersquick-delete', [AdminToolsController::class, 'deleteQuickQuotes']);
    Route::match(['get', 'post'], '/v/show-all-blogs.php', [AdminToolsController::class, 'blogs']);
    Route::post('/v/show-all-blogs/{blog}/delete', [AdminToolsController::class, 'deleteBlog']);
});

Route::get('/team', [TeamAuthController::class, 'showLogin']);
Route::get('/team/index.php', [TeamAuthController::class, 'showLogin']);
Route::post('/team/login', [TeamAuthController::class, 'login']);
Route::get('/team/logout.php', [TeamAuthController::class, 'logout']);

Route::middleware('team.auth')->group(function () {
    Route::get('/team/welcome.php', [TeamDashboardController::class, 'index']);
    Route::get('/team/queues/{queue}', [TeamOrdersController::class, 'queue']);
    Route::get('/team/under-process-orders.php', [TeamOrdersController::class, 'underProcess']);
    Route::post('/team/orders/{order}/working', [TeamOrdersController::class, 'saveWorking']);
    Route::get('/team/disapproved-orders.php', [TeamOrdersController::class, 'compatibilityQueueRedirect'])->defaults('queue', 'disapproved-orders');
    Route::get('/team/view-quotes.php', [TeamOrdersController::class, 'compatibilityQueueRedirect'])->defaults('queue', 'quotes');
    Route::get('/team/under-process-quick-orders.php', [TeamOrdersController::class, 'compatibilityQueueRedirect'])->defaults('queue', 'quick-quotes');

    Route::get('/team/view-order-detail.php', [TeamOrderDetailController::class, 'show']);
    Route::get('/team/orders/{order}/detail/{mode?}', [TeamOrderDetailController::class, 'showByRoute']);
    Route::post('/team/order-detail/comments', [TeamOrderDetailController::class, 'saveComment']);
    Route::post('/team/team-comments/{comment}/delete', [TeamOrderDetailController::class, 'deleteComment']);
    Route::post('/team/order-detail/upload', [TeamOrderDetailController::class, 'uploadAttachment']);
    Route::get('/team/attachments/{attachment}/download', [TeamOrderDetailController::class, 'downloadAttachment']);
    Route::get('/team/attachments/{attachment}/preview', [TeamOrderDetailController::class, 'previewAttachment']);
    Route::get('/team/attachments/{attachment}/preview/raw', [TeamOrderDetailController::class, 'previewAttachment'])->defaults('raw', 1);
    Route::post('/team/attachments/{attachment}/delete', [TeamOrderDetailController::class, 'deleteAttachment']);
    Route::get('/team/team_get_design_info_file.php', [TeamDesignInfoController::class, 'download']);
    Route::post('/team/order-detail/complete', [TeamOrderDetailController::class, 'complete']);

    Route::get('/team/view-order-quick-detail.php', [TeamQuickQuoteController::class, 'show']);
    Route::get('/team/quick-quotes/{order}/detail', [TeamQuickQuoteController::class, 'showByRoute']);
    Route::post('/team/quick-order/comments', [TeamQuickQuoteController::class, 'saveComment']);
    Route::post('/team/quick-comments/{comment}/delete', [TeamQuickQuoteController::class, 'deleteComment']);
    Route::post('/team/quick-order/upload', [TeamQuickQuoteController::class, 'uploadAttachment']);
    Route::get('/team/quick-attachments/{attachment}/download', [TeamQuickQuoteController::class, 'downloadAttachment']);
    Route::get('/team/quick-attachments/{attachment}/preview', [TeamQuickQuoteController::class, 'previewAttachment']);
    Route::get('/team/quick-attachments/{attachment}/preview/raw', [TeamQuickQuoteController::class, 'previewAttachment'])->defaults('raw', 1);
    Route::post('/team/quick-attachments/{attachment}/delete', [TeamQuickQuoteController::class, 'deleteAttachment']);
    Route::post('/team/quick-order/complete', [TeamQuickQuoteController::class, 'complete']);
});

Route::middleware(['team.auth', 'supervisor.auth'])->group(function () {
    Route::match(['get', 'post'], '/team/manage-team.php', [TeamSupervisorController::class, 'members']);
    Route::get('/team/team-member-detail.php', [TeamSupervisorController::class, 'memberDetail']);
    Route::get('/team/review-queue.php', [TeamSupervisorController::class, 'reviewQueue']);
    Route::get('/team/create-team.php', [TeamSupervisorController::class, 'memberForm']);
    Route::post('/team/create-team.php', [TeamSupervisorController::class, 'memberSave']);
    Route::get('/team/assign-order.php', [TeamSupervisorController::class, 'assignForm']);
    Route::post('/team/assign-order.php', [TeamSupervisorController::class, 'assignSave']);
    Route::post('/team/review-order.php', [TeamSupervisorController::class, 'markReviewed']);
});

Route::get('/uploads/{path}', [UploadController::class, 'show'])->where('path', '.*');
